---
- name: Create pihole directory {{ pihole_path }}
  ansible.builtin.file:
    path: "{{ pihole_path }}"
    state: directory
  become: true

- name: Create pihole persistent data directory
  ansible.builtin.file:
    path: "{{ pihole_path }}/data"
    state: directory
  become: true

- name: Create dnsmasq directory
  ansible.builtin.file:
    path: "{{ pihole_path }}/dnsmasq.d"
    state: directory
  become: true
