---
- name: Create pihole directory {{ pihole_path }}
  ansible.builtin.file:
    path: "{{ pihole_path }}"
    state: directory
  become: true

- name: Create pihole persistent data directory
  ansible.builtin.file:
    path: "{{ pihole_path }}/data"
    state: directory
  become: true

- name: Create dnsmasq directory
  ansible.builtin.file:
    path: "{{ pihole_path }}/dnsmasq.d"
    state: directory
  become: true

# use copy + force:no to "touch" only if doesn't exist
- name: Create setupVars.conf
  ansible.builtin.copy:
    content: ""
    dest: "{{ pihole_path }}/data/setupVars.conf"
    force: false
  become: true
