---
- name: Apt update cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr

- name: Configure systemd-resolved
  when: pihole_host_dns_port == 53
  ansible.builtin.import_tasks: systemd-resolved.yml

- name: Start pihole container
  ansible.builtin.import_tasks: pihole.yml
