---
- name: Docker pull pihole/pihole:latest
  community.general.docker_image:
    name: pihole/pihole:latest
    source: pull
    force_source: true

- name: Start pihole docker container
  community.general.docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    restart_policy: unless-stopped
    comparisons:
      '*': strict
    keep_volumes: false
    hostname: "{{ inventory_hostname }}"
    volumes:
      - "{{ pihole_path }}/data:/etc/pihole"
      - "{{ pihole_path }}/dnsmasq.d:/etc/dnsmasq.d"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports: "{{ (pihole_network_mode == 'bridge') | ternary(pihole_ports, []) }}"
    network_mode: "{{ pihole_network_mode }}"
    capabilities:
      - CAP_NET_BIND_SERVICE  # allow FTLDNS to bind to 53
      - CAP_SYS_NICE
    env:
      FTLCONF_LOCAL_IPV4: "{{ pihole_ipv4_address }}"
      FTLCONF_LOCAL_IPV6: "{{ pihole_ipv6_enabled | ternary(pihole_ipv6_address, '') }}"
      IPv6: "{{ pihole_ipv6_enabled | string }}"
      DNSMASQ_LISTENING: "all"
      DNSSEC: "{{ pihole_dnssec | string }}"
      QUERY_LOGGING: "{{ pihole_query_logging | string }}"
      PIHOLE_DNS_: "{{ pihole_dns }}"
      WEBPASSWORD: "{{ pihole_web_password }}"
      TZ: "{{ pihole_timezone }}"

- name: Wait for pihole service to start
  ansible.builtin.wait_for:
    port: 53
    timeout: 10
