---
- name: Disable systemd-resolved stub resolver
  register: systemd
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^DNSStubListener="
    line: "DNSStubListener={{ (pihole_host_dns_port == 53) | ternary('no', 'yes') }}"

- name: Restart systemd-resolved service
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: "{{ systemd.changed | ternary('restarted', 'started') }}"
