---
- name: Disable systemd-resolved stub resolver
  lineinfile:
    path:   /etc/systemd/resolved.conf
    regexp: "^DNSStubListener="
    line:   "DNSStubListener=no"
  become: true
  register: systemd

- name: Restart systemd-resolved service
  service:
    name: systemd-resolved
    status: restarted
  become: true
  when: systemd.changed
